project_id = "mtnjqsvwctabkzeihbki"

[functions.categorize-expense]
verify_jwt = false

[functions.generate-insights]
verify_jwt = false
import_map = "./import_map.json"

[functions.financial-chat]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.send-referral-email]
verify_jwt = false